openapi: 3.0.1
info:
  title: BPD HB Citizen API
  description: Api and Models
  version: v2
servers:
  - url: https://test.cstar.pagopa.it/bpd/hb/citizens/v2
paths:
  /:
    get:
      tags:
        - Bonus Pagamenti Digitali Citizen Controller
      summary: find
      description: find
      operationId: 5f7d6ba3990aecbeb9fadf99
      parameters:
        - name: x-request-id
          in: header
          description: UUID for request identification
          schema:
            type: string
        - name: id
          in: header
          description: id univoco che corrisponde al codice fiscale dell'utente
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/CitizenResource'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: ''
    patch:
      tags:
        - Bonus Pagamenti Digitali Citizen Controller
      summary: updatePaymentMethod
      description: updatePaymentMethod
      operationId: 5f7d6ba376aac3553a7d7997
      parameters:
        - name: x-request-id
          in: header
          description: UUID for request identification
          schema:
            type: string
      requestBody:
        description: citizen
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CitizenPatchDTO'
      responses:
        '401':
          description: Unauthorized
        '500':
          description: ''
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CitizenPatchResource'
        '400':
          description: Bad Request
    put:
      tags:
        - Bonus Pagamenti Digitali Citizen Controller
      summary: enrollmentCitizenHB
      description: enrollmentCitizenHB
      operationId: 5f7d6ba381543ac4387e97e1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CitizenDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CitizenResource'
        '401':
          description: ''
        '500':
          description: ''
    delete:
      tags:
        - Bonus Pagamenti Digitali Citizen Controller
      summary: delete
      operationId: delete
      parameters:
        - name: id
          in: header
          description: id univoco che corrisponde al codice fiscale dell'utente
          required: true
          schema:
            type: string
      responses:
        '204':
          description: ''
        '400':
          description: ''
        '500':
          description: ''
        '409':
          description: ''
  /ranking:
    get:
      tags:
        - Bonus Pagamenti Digitali Citizen Controller
      summary: findRanking
      description: findRanking
      operationId: 5fa3bdda19fc30cdec5493f8
      parameters:
        - name: awardPeriodId
          in: query
          description: identificativo univoco del periodo di premiazione
          schema:
            type: integer
        - name: x-request-id
          in: header
          description: UUID for request identification
          schema:
            type: string
        - name: id
          in: header
          description: id univoco che corrisponde al codice fiscale dell'utente
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/CitizenRankingResourceArray'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: ''
components:
  schemas:
    CitizenResource:
      title: CitizenResource
      required:
        - enabled
        - fiscalCode
        - payoffInstr
        - payoffInstrType
        - timestampTC
      type: object
      properties:
        enabled:
          type: boolean
          description: stato dell'abilitazione al servizio da parte del citizen
        fiscalCode:
          type: string
          description: 'id dell''utente, che corrisponde al codice fiscale'
        payoffInstr:
          type: string
          description: identificativo dello strumento di pagamento per la riscossione del premio
        payoffInstrType:
          type: string
          description: tipologia di strumento di pagamento per la riscossione del premio
        timestampTC:
          type: string
          description: timestamp dell'accettazione di T&C. FORMATO  ISO8601 yyyy-MM-ddTHH:mm:ss.SSSXXXXX
          format: date-time
    CitizenPatchResource:
      title: CitizenPatchResource
      required:
        - validationStatus
      type: object
      properties:
        validationStatus:
          type: string
          description: Stato di validazione a seguito della chiamata al servizio di checkIban.
      example:
        validationStatus: string
    CitizenRankingResource:
      title: CitizenRankingResource
      required:
        - totalParticipants
        - ranking
        - maxTransactionNumber
        - minTransactionNumber
        - transactionNumber
        - awardPeriodId
      type: object
      properties:
        totalParticipants:
          type: integer
          description: numero totale di partecipanti al Bonus Pagamenti Digitali
          format: int64
        ranking:
          type: integer
          description: posizione della graduatoria riferita al periodo di premiazione corrente
          format: int64
        maxTransactionNumber:
          type: integer
          description: Numero massimo di transazioni effettuate dagli utenti che rientrano nel 'rimborso speciale'
          format: int64
        minTransactionNumber:
          type: integer
          description: Numero minimo di transazioni effettuate dagli utenti che rientrano nel 'rimborso speciale'
          format: int64
        transactionNumber:
          type: integer
          description: Numero di transazioni effettuate dall’utente
          format: int64
        awardPeriodId:
          type: integer
          description: identificativo univoco del periodo di premiazione
          format: int64
    CitizenDeleteResource:
      title: CitizenDeleteResource
      required:
        - channel
      type: object
      properties:
        channel:
          type: string
          description: Canale che identifica univocamente l’issuer che invoca l’API sulla piattaforma. Valorizzato con il codice ABI dell’Issuer chiamante
      example:
        channel: string
    CitizenRankingResourceArray:
      type: array
      items:
        $ref: '#/components/schemas/CitizenRankingResource'
    CitizenDTO:
      title: CitizenDTO
      required:
        - id
      type: object
      properties:
        id:
          type: string
          description: 'id dell''utente, che corrisponde al codice fiscale'
    CitizenPatchDTO:
      title: CitizenPatchDTO
      required:
        - id
        - accountHolderCF
        - accountHolderName
        - accountHolderSurname
        - payoffInstr
        - payoffInstrType
      type: object
      properties:
        id:
          type: string
          description: 'id dell''utente, che corrisponde al codice fiscale'
        accountHolderCF:
          type: string
          description: CF dell'intestatario dell'IBAN
        accountHolderName:
          type: string
          description: Nome dell'intestatario dell'IBAN
        accountHolderSurname:
          type: string
          description: Cognome dell'intestatario dell'IBAN
        payoffInstr:
          type: string
          description: identificativo dello strumento di pagamento per la riscossione del premio
        payoffInstrType:
          enum:
            - IBAN
          type: string
          description: tipologia di strumento di pagamento per la riscossione del premio
      example:
        id: string
        accountHolderCF: string
        accountHolderName: string
        accountHolderSurname: string
        payoffInstr: string
        payoffInstrType: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]